package com.trevzhang.demo.test;

import com.alibaba.fastjson.JSON;
import com.alibaba.fastjson.JSONArray;
import com.alibaba.fastjson.JSONObject;
import com.alibaba.fastjson.JSONPath;
import com.alibaba.fastjson.TypeReference;
import java.util.Map;
import org.junit.Test;

/**
 * @author zhangchunguang.zcg
 * @since 2022/4/24 4:42 PM
 */
public class JSONTest {

    @Test
    public void testJSONParse() {
        String dataArr = "[\n"
            + "    {\n"
            + "      \"supplierName\": \"\",\n"
            + "      \"confirmTypeName\": \"即时确认\",\n"
            + "      \"routeCode\": \"FRC1053\",\n"
            + "      \"routeId\": \"1fd8464a-e02b-4735-a5b8-bd2a927f3a12\",\n"
            + "      \"bizChannelList\": [\n"
            + "        {\n"
            + "          \"channelType\": \"PLATFORM\",\n"
            + "          \"channelStatus\": \"ON_SALE\",\n"
            + "          \"class\": \"com.fliggy.scm.product.client.model.productChannel.FscBizChannelDTO\"\n"
            + "        },\n"
            + "        {\n"
            + "          \"channelType\": \"WECHAT_MINI_PROGRAM\",\n"
            + "          \"channelStatus\": \"OFF_SALE\",\n"
            + "          \"class\": \"com.fliggy.scm.product.client.model.productChannel.FscBizChannelDTO\"\n"
            + "        },\n"
            + "        {\n"
            + "          \"channelType\": \"FLIGGY\",\n"
            + "          \"channelStatus\": \"OFF_SALE\",\n"
            + "          \"class\": \"com.fliggy.scm.product.client.model.productChannel.FscBizChannelDTO\"\n"
            + "        }\n"
            + "      ],\n"
            + "      \"suggestChannelName\": \"阿信分销平台、飞猪\",\n"
            + "      \"ka\": false,\n"
            + "      \"class\": \"com.fliggy.scm.product.client.model.productChannel.FscRouteChannelListDTO\",\n"
            + "      \"routeName\": \"宇冬测试-线路-出境2日\"\n"
            + "    },\n"
            + "    {\n"
            + "      \"supplierName\": \"\",\n"
            + "      \"confirmTypeName\": \"即时确认\",\n"
            + "      \"routeCode\": \"FRC1052\",\n"
            + "      \"routeId\": \"8c6c2dc5-0469-4a42-b199-cbb8cb815ce1\",\n"
            + "      \"bizChannelList\": [\n"
            + "        {\n"
            + "          \"channelType\": \"PLATFORM\",\n"
            + "          \"channelStatus\": \"ON_SALE\",\n"
            + "          \"class\": \"com.fliggy.scm.product.client.model.productChannel.FscBizChannelDTO\"\n"
            + "        },\n"
            + "        {\n"
            + "          \"channelType\": \"WECHAT_MINI_PROGRAM\",\n"
            + "          \"channelStatus\": \"ON_SALE\",\n"
            + "          \"class\": \"com.fliggy.scm.product.client.model.productChannel.FscBizChannelDTO\"\n"
            + "        },\n"
            + "        {\n"
            + "          \"channelType\": \"FLIGGY\",\n"
            + "          \"channelStatus\": \"OFF_SALE\",\n"
            + "          \"class\": \"com.fliggy.scm.product.client.model.productChannel.FscBizChannelDTO\"\n"
            + "        }\n"
            + "      ],\n"
            + "      \"suggestChannelName\": \"阿信乐赚小程序\",\n"
            + "      \"ka\": false,\n"
            + "      \"class\": \"com.fliggy.scm.product.client.model.productChannel.FscRouteChannelListDTO\",\n"
            + "      \"routeName\": \"审核冒烟测试-复制-1-修改\"\n"
            + "    },\n"
            + "    {\n"
            + "      \"supplierName\": \"\",\n"
            + "      \"confirmTypeName\": \"即时确认\",\n"
            + "      \"routeCode\": \"FRC1051\",\n"
            + "      \"routeId\": \"88ac02f6-a114-4eae-a01d-64f6abc103e1\",\n"
            + "      \"bizChannelList\": [\n"
            + "        {\n"
            + "          \"channelType\": \"PLATFORM\",\n"
            + "          \"channelStatus\": \"ON_SALE\",\n"
            + "          \"class\": \"com.fliggy.scm.product.client.model.productChannel.FscBizChannelDTO\"\n"
            + "        },\n"
            + "        {\n"
            + "          \"channelType\": \"WECHAT_MINI_PROGRAM\",\n"
            + "          \"channelStatus\": \"ON_SALE\",\n"
            + "          \"class\": \"com.fliggy.scm.product.client.model.productChannel.FscBizChannelDTO\"\n"
            + "        },\n"
            + "        {\n"
            + "          \"channelType\": \"FLIGGY\",\n"
            + "          \"channelStatus\": \"OFF_SALE\",\n"
            + "          \"class\": \"com.fliggy.scm.product.client.model.productChannel.FscBizChannelDTO\"\n"
            + "        }\n"
            + "      ],\n"
            + "      \"suggestChannelName\": \"阿信分销平台、阿信乐赚小程序\",\n"
            + "      \"ka\": false,\n"
            + "      \"class\": \"com.fliggy.scm.product.client.model.productChannel.FscRouteChannelListDTO\",\n"
            + "      \"routeName\": \"测试mydiff\"\n"
            + "    },\n"
            + "    {\n"
            + "      \"supplierName\": \"\",\n"
            + "      \"confirmTypeName\": \"即时确认\",\n"
            + "      \"routeCode\": \"FRC1050\",\n"
            + "      \"routeId\": \"5dbae5e8-7d9d-46b3-8ed2-ff7682597d7f\",\n"
            + "      \"bizChannelList\": [\n"
            + "        {\n"
            + "          \"channelType\": \"PLATFORM\",\n"
            + "          \"channelStatus\": \"ON_SALE\",\n"
            + "          \"class\": \"com.fliggy.scm.product.client.model.productChannel.FscBizChannelDTO\"\n"
            + "        },\n"
            + "        {\n"
            + "          \"channelType\": \"WECHAT_MINI_PROGRAM\",\n"
            + "          \"channelStatus\": \"ON_SALE\",\n"
            + "          \"class\": \"com.fliggy.scm.product.client.model.productChannel.FscBizChannelDTO\"\n"
            + "        },\n"
            + "        {\n"
            + "          \"channelType\": \"FLIGGY\",\n"
            + "          \"channelStatus\": \"OFF_SALE\",\n"
            + "          \"class\": \"com.fliggy.scm.product.client.model.productChannel.FscBizChannelDTO\"\n"
            + "        }\n"
            + "      ],\n"
            + "      \"suggestChannelName\": \"阿信乐赚小程序\",\n"
            + "      \"ka\": false,\n"
            + "      \"class\": \"com.fliggy.scm.product.client.model.productChannel.FscRouteChannelListDTO\",\n"
            + "      \"routeName\": \"新增测试泰国品hq\"\n"
            + "    },\n"
            + "    {\n"
            + "      \"supplierName\": \"\",\n"
            + "      \"confirmTypeName\": \"即时确认\",\n"
            + "      \"routeCode\": \"FRC1049\",\n"
            + "      \"routeId\": \"e080dfd8-ceee-49a5-9be4-dd8b8905df79\",\n"
            + "      \"bizChannelList\": [\n"
            + "        {\n"
            + "          \"channelType\": \"PLATFORM\",\n"
            + "          \"channelStatus\": \"ON_SALE\",\n"
            + "          \"class\": \"com.fliggy.scm.product.client.model.productChannel.FscBizChannelDTO\"\n"
            + "        },\n"
            + "        {\n"
            + "          \"channelType\": \"WECHAT_MINI_PROGRAM\",\n"
            + "          \"channelStatus\": \"ON_SALE\",\n"
            + "          \"class\": \"com.fliggy.scm.product.client.model.productChannel.FscBizChannelDTO\"\n"
            + "        },\n"
            + "        {\n"
            + "          \"channelType\": \"FLIGGY\",\n"
            + "          \"channelStatus\": \"OFF_SALE\",\n"
            + "          \"class\": \"com.fliggy.scm.product.client.model.productChannel.FscBizChannelDTO\"\n"
            + "        }\n"
            + "      ],\n"
            + "      \"suggestChannelName\": \"阿信乐赚小程序\",\n"
            + "      \"ka\": false,\n"
            + "      \"class\": \"com.fliggy.scm.product.client.model.productChannel.FscRouteChannelListDTO\",\n"
            + "      \"routeName\": \"新增测试泰国品\"\n"
            + "    },\n"
            + "    {\n"
            + "      \"supplierName\": \"\",\n"
            + "      \"confirmTypeName\": \"即时确认\",\n"
            + "      \"routeCode\": \"FRC1048\",\n"
            + "      \"routeId\": \"9636d092-3e08-47c6-b3f3-b76a17ed8a69\",\n"
            + "      \"bizChannelList\": [\n"
            + "        {\n"
            + "          \"channelType\": \"PLATFORM\",\n"
            + "          \"channelStatus\": \"ON_SALE\",\n"
            + "          \"class\": \"com.fliggy.scm.product.client.model.productChannel.FscBizChannelDTO\"\n"
            + "        },\n"
            + "        {\n"
            + "          \"channelType\": \"WECHAT_MINI_PROGRAM\",\n"
            + "          \"channelStatus\": \"OFF_SALE\",\n"
            + "          \"class\": \"com.fliggy.scm.product.client.model.productChannel.FscBizChannelDTO\"\n"
            + "        },\n"
            + "        {\n"
            + "          \"channelType\": \"FLIGGY\",\n"
            + "          \"channelStatus\": \"OFF_SALE\",\n"
            + "          \"class\": \"com.fliggy.scm.product.client.model.productChannel.FscBizChannelDTO\"\n"
            + "        }\n"
            + "      ],\n"
            + "      \"suggestChannelName\": \"阿信分销平台、飞猪\",\n"
            + "      \"ka\": false,\n"
            + "      \"class\": \"com.fliggy.scm.product.client.model.productChannel.FscRouteChannelListDTO\",\n"
            + "      \"routeName\": \"新增测试泰国品\"\n"
            + "    },\n"
            + "    {\n"
            + "      \"supplierName\": \"\",\n"
            + "      \"confirmTypeName\": \"即时确认\",\n"
            + "      \"routeCode\": \"FRC1047\",\n"
            + "      \"routeId\": \"4315cc7e-87b6-4c40-9424-c4202d5370d4\",\n"
            + "      \"bizChannelList\": [\n"
            + "        {\n"
            + "          \"channelType\": \"PLATFORM\",\n"
            + "          \"channelStatus\": \"ON_SALE\",\n"
            + "          \"class\": \"com.fliggy.scm.product.client.model.productChannel.FscBizChannelDTO\"\n"
            + "        },\n"
            + "        {\n"
            + "          \"channelType\": \"WECHAT_MINI_PROGRAM\",\n"
            + "          \"channelStatus\": \"OFF_SALE\",\n"
            + "          \"class\": \"com.fliggy.scm.product.client.model.productChannel.FscBizChannelDTO\"\n"
            + "        },\n"
            + "        {\n"
            + "          \"channelType\": \"FLIGGY\",\n"
            + "          \"channelStatus\": \"OFF_SALE\",\n"
            + "          \"class\": \"com.fliggy.scm.product.client.model.productChannel.FscBizChannelDTO\"\n"
            + "        }\n"
            + "      ],\n"
            + "      \"suggestChannelName\": \"阿信分销平台、飞猪\",\n"
            + "      \"ka\": false,\n"
            + "      \"class\": \"com.fliggy.scm.product.client.model.productChannel.FscRouteChannelListDTO\",\n"
            + "      \"routeName\": \"上行发品调试专用测试品123\"\n"
            + "    },\n"
            + "    {\n"
            + "      \"supplierName\": \"\",\n"
            + "      \"confirmTypeName\": \"即时确认\",\n"
            + "      \"routeCode\": \"FRC1046\",\n"
            + "      \"routeId\": \"69dc5add-3326-4c41-b884-9ed1a81d350b\",\n"
            + "      \"bizChannelList\": [\n"
            + "        {\n"
            + "          \"channelType\": \"PLATFORM\",\n"
            + "          \"channelStatus\": \"ON_SALE\",\n"
            + "          \"class\": \"com.fliggy.scm.product.client.model.productChannel.FscBizChannelDTO\"\n"
            + "        },\n"
            + "        {\n"
            + "          \"channelType\": \"WECHAT_MINI_PROGRAM\",\n"
            + "          \"channelStatus\": \"OFF_SALE\",\n"
            + "          \"class\": \"com.fliggy.scm.product.client.model.productChannel.FscBizChannelDTO\"\n"
            + "        },\n"
            + "        {\n"
            + "          \"channelType\": \"FLIGGY\",\n"
            + "          \"channelStatus\": \"OFF_SALE\",\n"
            + "          \"class\": \"com.fliggy.scm.product.client.model.productChannel.FscBizChannelDTO\"\n"
            + "        }\n"
            + "      ],\n"
            + "      \"suggestChannelName\": \"阿信分销平台、飞猪\",\n"
            + "      \"ka\": false,\n"
            + "      \"class\": \"com.fliggy.scm.product.client.model.productChannel.FscRouteChannelListDTO\",\n"
            + "      \"routeName\": \"审核冒烟\"\n"
            + "    },\n"
            + "    {\n"
            + "      \"supplierName\": \"\",\n"
            + "      \"confirmTypeName\": \"即时确认\",\n"
            + "      \"routeCode\": \"FRC1045\",\n"
            + "      \"routeId\": \"211a69fc-913b-4b0e-9626-c62a66488ba5\",\n"
            + "      \"bizChannelList\": [\n"
            + "        {\n"
            + "          \"channelType\": \"PLATFORM\",\n"
            + "          \"channelStatus\": \"ON_SALE\",\n"
            + "          \"class\": \"com.fliggy.scm.product.client.model.productChannel.FscBizChannelDTO\"\n"
            + "        },\n"
            + "        {\n"
            + "          \"channelType\": \"WECHAT_MINI_PROGRAM\",\n"
            + "          \"channelStatus\": \"OFF_SALE\",\n"
            + "          \"class\": \"com.fliggy.scm.product.client.model.productChannel.FscBizChannelDTO\"\n"
            + "        },\n"
            + "        {\n"
            + "          \"channelType\": \"FLIGGY\",\n"
            + "          \"channelStatus\": \"OFF_SALE\",\n"
            + "          \"class\": \"com.fliggy.scm.product.client.model.productChannel.FscBizChannelDTO\"\n"
            + "        }\n"
            + "      ],\n"
            + "      \"suggestChannelName\": \"阿信分销平台\",\n"
            + "      \"ka\": false,\n"
            + "      \"class\": \"com.fliggy.scm.product.client.model.productChannel.FscRouteChannelListDTO\",\n"
            + "      \"routeName\": \"测试【轻享·杭州直飞】曼谷+芭提雅+莎美岛5晚6日游（杭州直飞，全程五钻酒店住宿，不走任何隐形购物店！）（副本）\"\n"
            + "    },\n"
            + "    {\n"
            + "      \"supplierName\": \"\",\n"
            + "      \"confirmTypeName\": \"即时确认\",\n"
            + "      \"routeCode\": \"FRC1044\",\n"
            + "      \"routeId\": \"d12e404c-1b92-4d1e-9473-c06f92f8cf71\",\n"
            + "      \"bizChannelList\": [\n"
            + "        {\n"
            + "          \"channelType\": \"PLATFORM\",\n"
            + "          \"channelStatus\": \"ON_SALE\",\n"
            + "          \"class\": \"com.fliggy.scm.product.client.model.productChannel.FscBizChannelDTO\"\n"
            + "        },\n"
            + "        {\n"
            + "          \"channelType\": \"WECHAT_MINI_PROGRAM\",\n"
            + "          \"channelStatus\": \"OFF_SALE\",\n"
            + "          \"class\": \"com.fliggy.scm.product.client.model.productChannel.FscBizChannelDTO\"\n"
            + "        },\n"
            + "        {\n"
            + "          \"channelType\": \"FLIGGY\",\n"
            + "          \"channelStatus\": \"OFF_SALE\",\n"
            + "          \"class\": \"com.fliggy.scm.product.client.model.productChannel.FscBizChannelDTO\"\n"
            + "        }\n"
            + "      ],\n"
            + "      \"suggestChannelName\": \"阿信分销平台\",\n"
            + "      \"ka\": false,\n"
            + "      \"class\": \"com.fliggy.scm.product.client.model.productChannel.FscRouteChannelListDTO\",\n"
            + "      \"routeName\": \"ss测试一下哈（联调测试-副本）\"\n"
            + "    },\n"
            + "    {\n"
            + "      \"supplierName\": \"\",\n"
            + "      \"confirmTypeName\": \"即时确认\",\n"
            + "      \"routeCode\": \"FRC1043\",\n"
            + "      \"routeId\": \"b3df705c-3227-4907-a3d0-015a0150c96d\",\n"
            + "      \"bizChannelList\": [\n"
            + "        {\n"
            + "          \"channelType\": \"PLATFORM\",\n"
            + "          \"channelStatus\": \"ON_SALE\",\n"
            + "          \"class\": \"com.fliggy.scm.product.client.model.productChannel.FscBizChannelDTO\"\n"
            + "        },\n"
            + "        {\n"
            + "          \"channelType\": \"WECHAT_MINI_PROGRAM\",\n"
            + "          \"channelStatus\": \"OFF_SALE\",\n"
            + "          \"class\": \"com.fliggy.scm.product.client.model.productChannel.FscBizChannelDTO\"\n"
            + "        },\n"
            + "        {\n"
            + "          \"channelType\": \"FLIGGY\",\n"
            + "          \"channelStatus\": \"OFF_SALE\",\n"
            + "          \"class\": \"com.fliggy.scm.product.client.model.productChannel.FscBizChannelDTO\"\n"
            + "        }\n"
            + "      ],\n"
            + "      \"suggestChannelName\": \"阿信分销平台\",\n"
            + "      \"ka\": false,\n"
            + "      \"class\": \"com.fliggy.scm.product.client.model.productChannel.FscRouteChannelListDTO\",\n"
            + "      \"routeName\": \"测试一下哈（联调测试）\"\n"
            + "    },\n"
            + "    {\n"
            + "      \"supplierName\": \"\",\n"
            + "      \"confirmTypeName\": \"即时确认\",\n"
            + "      \"routeCode\": \"FRC1042\",\n"
            + "      \"routeId\": \"3ad9855f-956d-4e77-9e09-2a47cd073329\",\n"
            + "      \"bizChannelList\": [\n"
            + "        {\n"
            + "          \"channelType\": \"PLATFORM\",\n"
            + "          \"channelStatus\": \"ON_SALE\",\n"
            + "          \"class\": \"com.fliggy.scm.product.client.model.productChannel.FscBizChannelDTO\"\n"
            + "        },\n"
            + "        {\n"
            + "          \"channelType\": \"WECHAT_MINI_PROGRAM\",\n"
            + "          \"channelStatus\": \"OFF_SALE\",\n"
            + "          \"class\": \"com.fliggy.scm.product.client.model.productChannel.FscBizChannelDTO\"\n"
            + "        },\n"
            + "        {\n"
            + "          \"channelType\": \"FLIGGY\",\n"
            + "          \"channelStatus\": \"OFF_SALE\",\n"
            + "          \"class\": \"com.fliggy.scm.product.client.model.productChannel.FscBizChannelDTO\"\n"
            + "        }\n"
            + "      ],\n"
            + "      \"suggestChannelName\": \"阿信分销平台\",\n"
            + "      \"ka\": false,\n"
            + "      \"class\": \"com.fliggy.scm.product.client.model.productChannel.FscRouteChannelListDTO\",\n"
            + "      \"routeName\": \"测试\"\n"
            + "    },\n"
            + "    {\n"
            + "      \"supplierName\": \"\",\n"
            + "      \"confirmTypeName\": \"即时确认\",\n"
            + "      \"routeCode\": \"FRC1041\",\n"
            + "      \"routeId\": \"b7eb1766-81d0-4cca-8d50-f03a994162f9\",\n"
            + "      \"bizChannelList\": [\n"
            + "        {\n"
            + "          \"channelType\": \"PLATFORM\",\n"
            + "          \"channelStatus\": \"ON_SALE\",\n"
            + "          \"class\": \"com.fliggy.scm.product.client.model.productChannel.FscBizChannelDTO\"\n"
            + "        },\n"
            + "        {\n"
            + "          \"channelType\": \"WECHAT_MINI_PROGRAM\",\n"
            + "          \"channelStatus\": \"OFF_SALE\",\n"
            + "          \"class\": \"com.fliggy.scm.product.client.model.productChannel.FscBizChannelDTO\"\n"
            + "        },\n"
            + "        {\n"
            + "          \"channelType\": \"FLIGGY\",\n"
            + "          \"channelStatus\": \"OFF_SALE\",\n"
            + "          \"class\": \"com.fliggy.scm.product.client.model.productChannel.FscBizChannelDTO\"\n"
            + "        }\n"
            + "      ],\n"
            + "      \"suggestChannelName\": \"阿信分销平台\",\n"
            + "      \"ka\": false,\n"
            + "      \"class\": \"com.fliggy.scm.product.client.model.productChannel.FscRouteChannelListDTO\",\n"
            + "      \"routeName\": \"测试【轻享·杭州直飞】曼谷+芭提雅+莎美岛5晚6日游（杭州直飞，全程五钻酒店住宿，不走任何隐形购物店！）\"\n"
            + "    },\n"
            + "    {\n"
            + "      \"supplierName\": \"\",\n"
            + "      \"confirmTypeName\": \"即时确认\",\n"
            + "      \"routeCode\": \"FRC1040\",\n"
            + "      \"routeId\": \"6b3a4638-542a-4801-adc9-454bb9a4b29e\",\n"
            + "      \"bizChannelList\": [\n"
            + "        {\n"
            + "          \"channelType\": \"PLATFORM\",\n"
            + "          \"channelStatus\": \"ON_SALE\",\n"
            + "          \"class\": \"com.fliggy.scm.product.client.model.productChannel.FscBizChannelDTO\"\n"
            + "        },\n"
            + "        {\n"
            + "          \"channelType\": \"WECHAT_MINI_PROGRAM\",\n"
            + "          \"channelStatus\": \"OFF_SALE\",\n"
            + "          \"class\": \"com.fliggy.scm.product.client.model.productChannel.FscBizChannelDTO\"\n"
            + "        },\n"
            + "        {\n"
            + "          \"channelType\": \"FLIGGY\",\n"
            + "          \"channelStatus\": \"OFF_SALE\",\n"
            + "          \"class\": \"com.fliggy.scm.product.client.model.productChannel.FscBizChannelDTO\"\n"
            + "        }\n"
            + "      ],\n"
            + "      \"suggestChannelName\": \"阿信分销平台\",\n"
            + "      \"ka\": false,\n"
            + "      \"class\": \"com.fliggy.scm.product.client.model.productChannel.FscRouteChannelListDTO\",\n"
            + "      \"routeName\": \"测试【轻享·杭州直飞】曼谷+芭提雅+莎美岛5晚6日游（杭州直飞，全程五钻酒店住宿，不走任何隐形购物店！）\"\n"
            + "    },\n"
            + "    {\n"
            + "      \"supplierName\": \"\",\n"
            + "      \"confirmTypeName\": \"即时确认\",\n"
            + "      \"routeCode\": \"FRC1039\",\n"
            + "      \"routeId\": \"3a61bc8b-19b7-4469-96ff-5092eb8f980c\",\n"
            + "      \"bizChannelList\": [\n"
            + "        {\n"
            + "          \"channelType\": \"PLATFORM\",\n"
            + "          \"channelStatus\": \"ON_SALE\",\n"
            + "          \"class\": \"com.fliggy.scm.product.client.model.productChannel.FscBizChannelDTO\"\n"
            + "        },\n"
            + "        {\n"
            + "          \"channelType\": \"WECHAT_MINI_PROGRAM\",\n"
            + "          \"channelStatus\": \"OFF_SALE\",\n"
            + "          \"class\": \"com.fliggy.scm.product.client.model.productChannel.FscBizChannelDTO\"\n"
            + "        },\n"
            + "        {\n"
            + "          \"channelType\": \"FLIGGY\",\n"
            + "          \"channelStatus\": \"OFF_SALE\",\n"
            + "          \"class\": \"com.fliggy.scm.product.client.model.productChannel.FscBizChannelDTO\"\n"
            + "        }\n"
            + "      ],\n"
            + "      \"suggestChannelName\": \"阿信分销平台\",\n"
            + "      \"ka\": false,\n"
            + "      \"class\": \"com.fliggy.scm.product.client.model.productChannel.FscRouteChannelListDTO\",\n"
            + "      \"routeName\": \"测试一下哈111111111111111111111111111111111111111111111111111111111111111111111\"\n"
            + "    },\n"
            + "    {\n"
            + "      \"supplierName\": \"\",\n"
            + "      \"confirmTypeName\": \"即时确认\",\n"
            + "      \"routeCode\": \"FRC1038\",\n"
            + "      \"routeId\": \"1cc3187d-af93-42b2-bebe-c075441a0d95\",\n"
            + "      \"bizChannelList\": [\n"
            + "        {\n"
            + "          \"channelType\": \"PLATFORM\",\n"
            + "          \"channelStatus\": \"ON_SALE\",\n"
            + "          \"class\": \"com.fliggy.scm.product.client.model.productChannel.FscBizChannelDTO\"\n"
            + "        },\n"
            + "        {\n"
            + "          \"channelType\": \"WECHAT_MINI_PROGRAM\",\n"
            + "          \"channelStatus\": \"OFF_SALE\",\n"
            + "          \"class\": \"com.fliggy.scm.product.client.model.productChannel.FscBizChannelDTO\"\n"
            + "        },\n"
            + "        {\n"
            + "          \"channelType\": \"FLIGGY\",\n"
            + "          \"channelStatus\": \"OFF_SALE\",\n"
            + "          \"class\": \"com.fliggy.scm.product.client.model.productChannel.FscBizChannelDTO\"\n"
            + "        }\n"
            + "      ],\n"
            + "      \"suggestChannelName\": \"阿信分销平台\",\n"
            + "      \"ka\": false,\n"
            + "      \"class\": \"com.fliggy.scm.product.client.model.productChannel.FscRouteChannelListDTO\",\n"
            + "      \"routeName\": \"审核测试-不要用\"\n"
            + "    },\n"
            + "    {\n"
            + "      \"supplierName\": \"\",\n"
            + "      \"confirmTypeName\": \"即时确认\",\n"
            + "      \"routeCode\": \"FRC1034\",\n"
            + "      \"routeId\": \"bcefe86c-983c-441e-96e8-f11d91a70946\",\n"
            + "      \"bizChannelList\": [\n"
            + "        {\n"
            + "          \"channelType\": \"PLATFORM\",\n"
            + "          \"channelStatus\": \"ON_SALE\",\n"
            + "          \"class\": \"com.fliggy.scm.product.client.model.productChannel.FscBizChannelDTO\"\n"
            + "        },\n"
            + "        {\n"
            + "          \"channelType\": \"WECHAT_MINI_PROGRAM\",\n"
            + "          \"channelStatus\": \"OFF_SALE\",\n"
            + "          \"class\": \"com.fliggy.scm.product.client.model.productChannel.FscBizChannelDTO\"\n"
            + "        },\n"
            + "        {\n"
            + "          \"channelType\": \"FLIGGY\",\n"
            + "          \"channelStatus\": \"OFF_SALE\",\n"
            + "          \"class\": \"com.fliggy.scm.product.client.model.productChannel.FscBizChannelDTO\"\n"
            + "        }\n"
            + "      ],\n"
            + "      \"suggestChannelName\": \"阿信分销平台\",\n"
            + "      \"ka\": false,\n"
            + "      \"class\": \"com.fliggy.scm.product.client.model.productChannel.FscRouteChannelListDTO\",\n"
            + "      \"routeName\": \"测试一下哈\"\n"
            + "    },\n"
            + "    {\n"
            + "      \"supplierName\": \"\",\n"
            + "      \"confirmTypeName\": \"二次确认\",\n"
            + "      \"routeCode\": \"FRC1033\",\n"
            + "      \"routeId\": \"2a0b6c55-6f8d-4c05-ba72-b1c1ad574a14\",\n"
            + "      \"bizChannelList\": [\n"
            + "        {\n"
            + "          \"channelType\": \"PLATFORM\",\n"
            + "          \"channelStatus\": \"ON_SALE\",\n"
            + "          \"class\": \"com.fliggy.scm.product.client.model.productChannel.FscBizChannelDTO\"\n"
            + "        },\n"
            + "        {\n"
            + "          \"channelType\": \"WECHAT_MINI_PROGRAM\",\n"
            + "          \"channelStatus\": \"ON_SALE\",\n"
            + "          \"class\": \"com.fliggy.scm.product.client.model.productChannel.FscBizChannelDTO\"\n"
            + "        },\n"
            + "        {\n"
            + "          \"channelType\": \"FLIGGY\",\n"
            + "          \"channelStatus\": \"OFF_SALE\",\n"
            + "          \"class\": \"com.fliggy.scm.product.client.model.productChannel.FscBizChannelDTO\"\n"
            + "        }\n"
            + "      ],\n"
            + "      \"suggestChannelName\": \"阿信乐赚小程序\",\n"
            + "      \"ka\": false,\n"
            + "      \"class\": \"com.fliggy.scm.product.client.model.productChannel.FscRouteChannelListDTO\",\n"
            + "      \"routeName\": \"测试test\"\n"
            + "    },\n"
            + "    {\n"
            + "      \"supplierName\": \"\",\n"
            + "      \"confirmTypeName\": \"即时确认\",\n"
            + "      \"routeCode\": \"FRC1032\",\n"
            + "      \"routeId\": \"ce7f2c04-79aa-418a-8b51-941d299217db\",\n"
            + "      \"bizChannelList\": [\n"
            + "        {\n"
            + "          \"channelType\": \"PLATFORM\",\n"
            + "          \"channelStatus\": \"ON_SALE\",\n"
            + "          \"class\": \"com.fliggy.scm.product.client.model.productChannel.FscBizChannelDTO\"\n"
            + "        },\n"
            + "        {\n"
            + "          \"channelType\": \"WECHAT_MINI_PROGRAM\",\n"
            + "          \"channelStatus\": \"OFF_SALE\",\n"
            + "          \"class\": \"com.fliggy.scm.product.client.model.productChannel.FscBizChannelDTO\"\n"
            + "        },\n"
            + "        {\n"
            + "          \"channelType\": \"FLIGGY\",\n"
            + "          \"channelStatus\": \"OFF_SALE\",\n"
            + "          \"class\": \"com.fliggy.scm.product.client.model.productChannel.FscBizChannelDTO\"\n"
            + "        }\n"
            + "      ],\n"
            + "      \"suggestChannelName\": null,\n"
            + "      \"ka\": false,\n"
            + "      \"class\": \"com.fliggy.scm.product.client.model.productChannel.FscRouteChannelListDTO\",\n"
            + "      \"routeName\": \"北京  1日 出发地参团\"\n"
            + "    },\n"
            + "    {\n"
            + "      \"supplierName\": \"\",\n"
            + "      \"confirmTypeName\": \"即时确认\",\n"
            + "      \"routeCode\": \"FRC1031\",\n"
            + "      \"routeId\": \"af2a6c5a-737e-4c1d-b3b0-971bcadce68c\",\n"
            + "      \"bizChannelList\": [\n"
            + "        {\n"
            + "          \"channelType\": \"PLATFORM\",\n"
            + "          \"channelStatus\": \"ON_SALE\",\n"
            + "          \"class\": \"com.fliggy.scm.product.client.model.productChannel.FscBizChannelDTO\"\n"
            + "        },\n"
            + "        {\n"
            + "          \"channelType\": \"WECHAT_MINI_PROGRAM\",\n"
            + "          \"channelStatus\": \"OFF_SALE\",\n"
            + "          \"class\": \"com.fliggy.scm.product.client.model.productChannel.FscBizChannelDTO\"\n"
            + "        },\n"
            + "        {\n"
            + "          \"channelType\": \"FLIGGY\",\n"
            + "          \"channelStatus\": \"OFF_SALE\",\n"
            + "          \"class\": \"com.fliggy.scm.product.client.model.productChannel.FscBizChannelDTO\"\n"
            + "        }\n"
            + "      ],\n"
            + "      \"suggestChannelName\": \"阿信分销平台\",\n"
            + "      \"ka\": false,\n"
            + "      \"class\": \"com.fliggy.scm.product.client.model.productChannel.FscRouteChannelListDTO\",\n"
            + "      \"routeName\": \"测试一下渠道问题，复制品，文本审核one次\"\n"
            + "    },\n"
            + "    {\n"
            + "      \"supplierName\": \"\",\n"
            + "      \"confirmTypeName\": \"二次确认\",\n"
            + "      \"routeCode\": \"FRC1030\",\n"
            + "      \"routeId\": \"7c678eee-dfae-460e-81c3-52014a7bacac\",\n"
            + "      \"bizChannelList\": [\n"
            + "        {\n"
            + "          \"channelType\": \"PLATFORM\",\n"
            + "          \"channelStatus\": \"ON_SALE\",\n"
            + "          \"class\": \"com.fliggy.scm.product.client.model.productChannel.FscBizChannelDTO\"\n"
            + "        },\n"
            + "        {\n"
            + "          \"channelType\": \"WECHAT_MINI_PROGRAM\",\n"
            + "          \"channelStatus\": \"OFF_SALE\",\n"
            + "          \"class\": \"com.fliggy.scm.product.client.model.productChannel.FscBizChannelDTO\"\n"
            + "        },\n"
            + "        {\n"
            + "          \"channelType\": \"FLIGGY\",\n"
            + "          \"channelStatus\": \"OFF_SALE\",\n"
            + "          \"class\": \"com.fliggy.scm.product.client.model.productChannel.FscBizChannelDTO\"\n"
            + "        }\n"
            + "      ],\n"
            + "      \"suggestChannelName\": null,\n"
            + "      \"ka\": false,\n"
            + "      \"class\": \"com.fliggy.scm.product.client.model.productChannel.FscRouteChannelListDTO\",\n"
            + "      \"routeName\": \"发品专用测试，测试草稿箱689号发布,再试一下复制\"\n"
            + "    },\n"
            + "    {\n"
            + "      \"supplierName\": \"\",\n"
            + "      \"confirmTypeName\": \"二次确认\",\n"
            + "      \"routeCode\": \"FRC1029\",\n"
            + "      \"routeId\": \"6483dbcb-910e-4ade-98a5-5fcaa3d79878\",\n"
            + "      \"bizChannelList\": [\n"
            + "        {\n"
            + "          \"channelType\": \"PLATFORM\",\n"
            + "          \"channelStatus\": \"ON_SALE\",\n"
            + "          \"class\": \"com.fliggy.scm.product.client.model.productChannel.FscBizChannelDTO\"\n"
            + "        },\n"
            + "        {\n"
            + "          \"channelType\": \"WECHAT_MINI_PROGRAM\",\n"
            + "          \"channelStatus\": \"ON_SALE\",\n"
            + "          \"class\": \"com.fliggy.scm.product.client.model.productChannel.FscBizChannelDTO\"\n"
            + "        },\n"
            + "        {\n"
            + "          \"channelType\": \"FLIGGY\",\n"
            + "          \"channelStatus\": \"OFF_SALE\",\n"
            + "          \"class\": \"com.fliggy.scm.product.client.model.productChannel.FscBizChannelDTO\"\n"
            + "        }\n"
            + "      ],\n"
            + "      \"suggestChannelName\": \"阿信乐赚小程序\",\n"
            + "      \"ka\": false,\n"
            + "      \"class\": \"com.fliggy.scm.product.client.model.productChannel.FscRouteChannelListDTO\",\n"
            + "      \"routeName\": \"发品专用测试，测试草稿箱专用1号修改111\"\n"
            + "    },\n"
            + "    {\n"
            + "      \"supplierName\": \"\",\n"
            + "      \"confirmTypeName\": \"二次确认\",\n"
            + "      \"routeCode\": \"FRC1028\",\n"
            + "      \"routeId\": \"9b821131-1bfd-4a25-b83b-3fd9c2ec606b\",\n"
            + "      \"bizChannelList\": [\n"
            + "        {\n"
            + "          \"channelType\": \"PLATFORM\",\n"
            + "          \"channelStatus\": \"ON_SALE\",\n"
            + "          \"class\": \"com.fliggy.scm.product.client.model.productChannel.FscBizChannelDTO\"\n"
            + "        },\n"
            + "        {\n"
            + "          \"channelType\": \"WECHAT_MINI_PROGRAM\",\n"
            + "          \"channelStatus\": \"ON_SALE\",\n"
            + "          \"class\": \"com.fliggy.scm.product.client.model.productChannel.FscBizChannelDTO\"\n"
            + "        },\n"
            + "        {\n"
            + "          \"channelType\": \"FLIGGY\",\n"
            + "          \"channelStatus\": \"OFF_SALE\",\n"
            + "          \"class\": \"com.fliggy.scm.product.client.model.productChannel.FscBizChannelDTO\"\n"
            + "        }\n"
            + "      ],\n"
            + "      \"suggestChannelName\": \"阿信乐赚小程序\",\n"
            + "      \"ka\": false,\n"
            + "      \"class\": \"com.fliggy.scm.product.client.model.productChannel.FscRouteChannelListDTO\",\n"
            + "      \"routeName\": \"发品专用测试，测试草稿箱专用1号修改\"\n"
            + "    },\n"
            + "    {\n"
            + "      \"supplierName\": \"\",\n"
            + "      \"confirmTypeName\": \"二次确认\",\n"
            + "      \"routeCode\": \"FRC1027\",\n"
            + "      \"routeId\": \"b7bb9082-0544-4e53-ba7a-6f3664af2dc1\",\n"
            + "      \"bizChannelList\": [\n"
            + "        {\n"
            + "          \"channelType\": \"PLATFORM\",\n"
            + "          \"channelStatus\": \"ON_SALE\",\n"
            + "          \"class\": \"com.fliggy.scm.product.client.model.productChannel.FscBizChannelDTO\"\n"
            + "        },\n"
            + "        {\n"
            + "          \"channelType\": \"WECHAT_MINI_PROGRAM\",\n"
            + "          \"channelStatus\": \"ON_SALE\",\n"
            + "          \"class\": \"com.fliggy.scm.product.client.model.productChannel.FscBizChannelDTO\"\n"
            + "        },\n"
            + "        {\n"
            + "          \"channelType\": \"FLIGGY\",\n"
            + "          \"channelStatus\": \"OFF_SALE\",\n"
            + "          \"class\": \"com.fliggy.scm.product.client.model.productChannel.FscBizChannelDTO\"\n"
            + "        }\n"
            + "      ],\n"
            + "      \"suggestChannelName\": \"阿信乐赚小程序\",\n"
            + "      \"ka\": false,\n"
            + "      \"class\": \"com.fliggy.scm.product.client.model.productChannel.FscRouteChannelListDTO\",\n"
            + "      \"routeName\": \"发品专用测试，测试草稿箱1号发布\"\n"
            + "    },\n"
            + "    {\n"
            + "      \"supplierName\": \"\",\n"
            + "      \"confirmTypeName\": \"二次确认\",\n"
            + "      \"routeCode\": \"\",\n"
            + "      \"routeId\": \"4732a9e6-25b3-4fc1-bac4-a93dfecc8f05\",\n"
            + "      \"bizChannelList\": [\n"
            + "        {\n"
            + "          \"channelType\": \"PLATFORM\",\n"
            + "          \"channelStatus\": \"ON_SALE\",\n"
            + "          \"class\": \"com.fliggy.scm.product.client.model.productChannel.FscBizChannelDTO\"\n"
            + "        },\n"
            + "        {\n"
            + "          \"channelType\": \"WECHAT_MINI_PROGRAM\",\n"
            + "          \"channelStatus\": \"ON_SALE\",\n"
            + "          \"class\": \"com.fliggy.scm.product.client.model.productChannel.FscBizChannelDTO\"\n"
            + "        },\n"
            + "        {\n"
            + "          \"channelType\": \"FLIGGY\",\n"
            + "          \"channelStatus\": \"OFF_SALE\",\n"
            + "          \"class\": \"com.fliggy.scm.product.client.model.productChannel.FscBizChannelDTO\"\n"
            + "        }\n"
            + "      ],\n"
            + "      \"suggestChannelName\": \"阿信乐赚小程序\",\n"
            + "      \"ka\": false,\n"
            + "      \"class\": \"com.fliggy.scm.product.client.model.productChannel.FscRouteChannelListDTO\",\n"
            + "      \"routeName\": \"发品专用测试，这个好像是手工发品4,验证下复制的问题\"\n"
            + "    },\n"
            + "    {\n"
            + "      \"supplierName\": \"杭州阿信巴拉巴拉公司\",\n"
            + "      \"confirmTypeName\": \"即时确认\",\n"
            + "      \"routeCode\": \"\",\n"
            + "      \"routeId\": \"94eb6c75-27bf-4696-9584-dfc228f00c32\",\n"
            + "      \"bizChannelList\": [\n"
            + "        {\n"
            + "          \"channelType\": \"PLATFORM\",\n"
            + "          \"channelStatus\": \"ON_SALE\",\n"
            + "          \"class\": \"com.fliggy.scm.product.client.model.productChannel.FscBizChannelDTO\"\n"
            + "        },\n"
            + "        {\n"
            + "          \"channelType\": \"WECHAT_MINI_PROGRAM\",\n"
            + "          \"channelStatus\": \"ON_SALE\",\n"
            + "          \"class\": \"com.fliggy.scm.product.client.model.productChannel.FscBizChannelDTO\"\n"
            + "        },\n"
            + "        {\n"
            + "          \"channelType\": \"FLIGGY\",\n"
            + "          \"channelStatus\": \"OFF_SALE\",\n"
            + "          \"class\": \"com.fliggy.scm.product.client.model.productChannel.FscBizChannelDTO\"\n"
            + "        }\n"
            + "      ],\n"
            + "      \"suggestChannelName\": \"阿信乐赚小程序\",\n"
            + "      \"ka\": false,\n"
            + "      \"class\": \"com.fliggy.scm.product.client.model.productChannel.FscRouteChannelListDTO\",\n"
            + "      \"routeName\": \"这个别用，发品专用测试,看下渠道信息展示\"\n"
            + "    },\n"
            + "    {\n"
            + "      \"supplierName\": \"杭州阿信巴拉巴拉公司\",\n"
            + "      \"confirmTypeName\": \"即时确认\",\n"
            + "      \"routeCode\": \"FRC1024\",\n"
            + "      \"routeId\": \"c40f9500-dbcb-4b27-8977-3acf37c5e0b1\",\n"
            + "      \"bizChannelList\": [\n"
            + "        {\n"
            + "          \"channelType\": \"PLATFORM\",\n"
            + "          \"channelStatus\": \"ON_SALE\",\n"
            + "          \"class\": \"com.fliggy.scm.product.client.model.productChannel.FscBizChannelDTO\"\n"
            + "        },\n"
            + "        {\n"
            + "          \"channelType\": \"WECHAT_MINI_PROGRAM\",\n"
            + "          \"channelStatus\": \"ON_SALE\",\n"
            + "          \"class\": \"com.fliggy.scm.product.client.model.productChannel.FscBizChannelDTO\"\n"
            + "        },\n"
            + "        {\n"
            + "          \"channelType\": \"FLIGGY\",\n"
            + "          \"channelStatus\": \"OFF_SALE\",\n"
            + "          \"class\": \"com.fliggy.scm.product.client.model.productChannel.FscBizChannelDTO\"\n"
            + "        }\n"
            + "      ],\n"
            + "      \"suggestChannelName\": \"阿信乐赚小程序\",\n"
            + "      \"ka\": false,\n"
            + "      \"class\": \"com.fliggy.scm.product.client.model.productChannel.FscRouteChannelListDTO\",\n"
            + "      \"routeName\": \"杭州-考文垂 6天5夜超级豪华策士线路\"\n"
            + "    },\n"
            + "    {\n"
            + "      \"supplierName\": \"杭州阿信巴拉巴拉公司\",\n"
            + "      \"confirmTypeName\": \"即时确认\",\n"
            + "      \"routeCode\": \"FRC1023\",\n"
            + "      \"routeId\": \"ad25ef91-7dd9-48dd-8970-bad4d4f25e41\",\n"
            + "      \"bizChannelList\": [\n"
            + "        {\n"
            + "          \"channelType\": \"PLATFORM\",\n"
            + "          \"channelStatus\": \"ON_SALE\",\n"
            + "          \"class\": \"com.fliggy.scm.product.client.model.productChannel.FscBizChannelDTO\"\n"
            + "        },\n"
            + "        {\n"
            + "          \"channelType\": \"WECHAT_MINI_PROGRAM\",\n"
            + "          \"channelStatus\": \"ON_SALE\",\n"
            + "          \"class\": \"com.fliggy.scm.product.client.model.productChannel.FscBizChannelDTO\"\n"
            + "        },\n"
            + "        {\n"
            + "          \"channelType\": \"FLIGGY\",\n"
            + "          \"channelStatus\": \"OFF_SALE\",\n"
            + "          \"class\": \"com.fliggy.scm.product.client.model.productChannel.FscBizChannelDTO\"\n"
            + "        }\n"
            + "      ],\n"
            + "      \"suggestChannelName\": \"阿信乐赚小程序\",\n"
            + "      \"ka\": false,\n"
            + "      \"class\": \"com.fliggy.scm.product.client.model.productChannel.FscRouteChannelListDTO\",\n"
            + "      \"routeName\": \"杭州-考文垂 6天5夜超级豪华策士线路\"\n"
            + "    },\n"
            + "    {\n"
            + "      \"supplierName\": \"杭州阿信巴拉巴拉公司\",\n"
            + "      \"confirmTypeName\": \"即时确认\",\n"
            + "      \"routeCode\": \"FRC1022\",\n"
            + "      \"routeId\": \"307cbdab-8f66-4844-b416-0216f2193761\",\n"
            + "      \"bizChannelList\": [\n"
            + "        {\n"
            + "          \"channelType\": \"PLATFORM\",\n"
            + "          \"channelStatus\": \"ON_SALE\",\n"
            + "          \"class\": \"com.fliggy.scm.product.client.model.productChannel.FscBizChannelDTO\"\n"
            + "        },\n"
            + "        {\n"
            + "          \"channelType\": \"WECHAT_MINI_PROGRAM\",\n"
            + "          \"channelStatus\": \"ON_SALE\",\n"
            + "          \"class\": \"com.fliggy.scm.product.client.model.productChannel.FscBizChannelDTO\"\n"
            + "        },\n"
            + "        {\n"
            + "          \"channelType\": \"FLIGGY\",\n"
            + "          \"channelStatus\": \"OFF_SALE\",\n"
            + "          \"class\": \"com.fliggy.scm.product.client.model.productChannel.FscBizChannelDTO\"\n"
            + "        }\n"
            + "      ],\n"
            + "      \"suggestChannelName\": \"阿信乐赚小程序\",\n"
            + "      \"ka\": false,\n"
            + "      \"class\": \"com.fliggy.scm.product.client.model.productChannel.FscRouteChannelListDTO\",\n"
            + "      \"routeName\": \"杭州-考文垂 6天5夜超级豪华策士线路\"\n"
            + "    },\n"
            + "    {\n"
            + "      \"supplierName\": \"杭州阿信巴拉巴拉公司\",\n"
            + "      \"confirmTypeName\": \"即时确认\",\n"
            + "      \"routeCode\": \"FRC1021\",\n"
            + "      \"routeId\": \"240d7ea4-5916-4b94-8e47-270ee9e7ffef\",\n"
            + "      \"bizChannelList\": [\n"
            + "        {\n"
            + "          \"channelType\": \"PLATFORM\",\n"
            + "          \"channelStatus\": \"ON_SALE\",\n"
            + "          \"class\": \"com.fliggy.scm.product.client.model.productChannel.FscBizChannelDTO\"\n"
            + "        },\n"
            + "        {\n"
            + "          \"channelType\": \"WECHAT_MINI_PROGRAM\",\n"
            + "          \"channelStatus\": \"ON_SALE\",\n"
            + "          \"class\": \"com.fliggy.scm.product.client.model.productChannel.FscBizChannelDTO\"\n"
            + "        },\n"
            + "        {\n"
            + "          \"channelType\": \"FLIGGY\",\n"
            + "          \"channelStatus\": \"OFF_SALE\",\n"
            + "          \"class\": \"com.fliggy.scm.product.client.model.productChannel.FscBizChannelDTO\"\n"
            + "        }\n"
            + "      ],\n"
            + "      \"suggestChannelName\": \"阿信乐赚小程序\",\n"
            + "      \"ka\": false,\n"
            + "      \"class\": \"com.fliggy.scm.product.client.model.productChannel.FscRouteChannelListDTO\",\n"
            + "      \"routeName\": \"杭州-考文垂 6天5夜超级豪华策士线路\"\n"
            + "    },\n"
            + "    {\n"
            + "      \"supplierName\": \"杭州阿信巴拉巴拉公司\",\n"
            + "      \"confirmTypeName\": \"即时确认\",\n"
            + "      \"routeCode\": \"FRC1020\",\n"
            + "      \"routeId\": \"3d240f2f-c488-4ff7-918d-6157b68faf92\",\n"
            + "      \"bizChannelList\": [\n"
            + "        {\n"
            + "          \"channelType\": \"PLATFORM\",\n"
            + "          \"channelStatus\": \"ON_SALE\",\n"
            + "          \"class\": \"com.fliggy.scm.product.client.model.productChannel.FscBizChannelDTO\"\n"
            + "        },\n"
            + "        {\n"
            + "          \"channelType\": \"WECHAT_MINI_PROGRAM\",\n"
            + "          \"channelStatus\": \"ON_SALE\",\n"
            + "          \"class\": \"com.fliggy.scm.product.client.model.productChannel.FscBizChannelDTO\"\n"
            + "        },\n"
            + "        {\n"
            + "          \"channelType\": \"FLIGGY\",\n"
            + "          \"channelStatus\": \"OFF_SALE\",\n"
            + "          \"class\": \"com.fliggy.scm.product.client.model.productChannel.FscBizChannelDTO\"\n"
            + "        }\n"
            + "      ],\n"
            + "      \"suggestChannelName\": \"阿信乐赚小程序\",\n"
            + "      \"ka\": false,\n"
            + "      \"class\": \"com.fliggy.scm.product.client.model.productChannel.FscRouteChannelListDTO\",\n"
            + "      \"routeName\": \"杭州-考文垂 6天5夜超级豪华策士线路\"\n"
            + "    },\n"
            + "    {\n"
            + "      \"supplierName\": \"杭州阿信巴拉巴拉公司\",\n"
            + "      \"confirmTypeName\": \"即时确认\",\n"
            + "      \"routeCode\": \"FRC1019\",\n"
            + "      \"routeId\": \"02ae6907-fbfa-44c1-ae9e-c9a5f9bbb951\",\n"
            + "      \"bizChannelList\": [\n"
            + "        {\n"
            + "          \"channelType\": \"PLATFORM\",\n"
            + "          \"channelStatus\": \"ON_SALE\",\n"
            + "          \"class\": \"com.fliggy.scm.product.client.model.productChannel.FscBizChannelDTO\"\n"
            + "        },\n"
            + "        {\n"
            + "          \"channelType\": \"WECHAT_MINI_PROGRAM\",\n"
            + "          \"channelStatus\": \"ON_SALE\",\n"
            + "          \"class\": \"com.fliggy.scm.product.client.model.productChannel.FscBizChannelDTO\"\n"
            + "        },\n"
            + "        {\n"
            + "          \"channelType\": \"FLIGGY\",\n"
            + "          \"channelStatus\": \"OFF_SALE\",\n"
            + "          \"class\": \"com.fliggy.scm.product.client.model.productChannel.FscBizChannelDTO\"\n"
            + "        }\n"
            + "      ],\n"
            + "      \"suggestChannelName\": \"阿信乐赚小程序\",\n"
            + "      \"ka\": false,\n"
            + "      \"class\": \"com.fliggy.scm.product.client.model.productChannel.FscRouteChannelListDTO\",\n"
            + "      \"routeName\": \"杭州-考文垂 6天5夜超级豪华策士线路\"\n"
            + "    },\n"
            + "    {\n"
            + "      \"supplierName\": \"杭州阿信巴拉巴拉公司\",\n"
            + "      \"confirmTypeName\": \"即时确认\",\n"
            + "      \"routeCode\": \"FRC1018\",\n"
            + "      \"routeId\": \"270a05ff-069d-4b27-bfd6-4042a8376fbb\",\n"
            + "      \"bizChannelList\": [\n"
            + "        {\n"
            + "          \"channelType\": \"PLATFORM\",\n"
            + "          \"channelStatus\": \"ON_SALE\",\n"
            + "          \"class\": \"com.fliggy.scm.product.client.model.productChannel.FscBizChannelDTO\"\n"
            + "        },\n"
            + "        {\n"
            + "          \"channelType\": \"WECHAT_MINI_PROGRAM\",\n"
            + "          \"channelStatus\": \"ON_SALE\",\n"
            + "          \"class\": \"com.fliggy.scm.product.client.model.productChannel.FscBizChannelDTO\"\n"
            + "        },\n"
            + "        {\n"
            + "          \"channelType\": \"FLIGGY\",\n"
            + "          \"channelStatus\": \"OFF_SALE\",\n"
            + "          \"class\": \"com.fliggy.scm.product.client.model.productChannel.FscBizChannelDTO\"\n"
            + "        }\n"
            + "      ],\n"
            + "      \"suggestChannelName\": \"阿信乐赚小程序\",\n"
            + "      \"ka\": false,\n"
            + "      \"class\": \"com.fliggy.scm.product.client.model.productChannel.FscRouteChannelListDTO\",\n"
            + "      \"routeName\": \"杭州-考文垂 6天5夜超级豪华策士线路\"\n"
            + "    },\n"
            + "    {\n"
            + "      \"supplierName\": \"杭州阿信巴拉巴拉公司\",\n"
            + "      \"confirmTypeName\": \"即时确认\",\n"
            + "      \"routeCode\": \"FRC1017\",\n"
            + "      \"routeId\": \"fe7dac94-8221-4e3c-8dd1-58e0db35b2c4\",\n"
            + "      \"bizChannelList\": [\n"
            + "        {\n"
            + "          \"channelType\": \"PLATFORM\",\n"
            + "          \"channelStatus\": \"ON_SALE\",\n"
            + "          \"class\": \"com.fliggy.scm.product.client.model.productChannel.FscBizChannelDTO\"\n"
            + "        },\n"
            + "        {\n"
            + "          \"channelType\": \"WECHAT_MINI_PROGRAM\",\n"
            + "          \"channelStatus\": \"ON_SALE\",\n"
            + "          \"class\": \"com.fliggy.scm.product.client.model.productChannel.FscBizChannelDTO\"\n"
            + "        },\n"
            + "        {\n"
            + "          \"channelType\": \"FLIGGY\",\n"
            + "          \"channelStatus\": \"OFF_SALE\",\n"
            + "          \"class\": \"com.fliggy.scm.product.client.model.productChannel.FscBizChannelDTO\"\n"
            + "        }\n"
            + "      ],\n"
            + "      \"suggestChannelName\": \"阿信乐赚小程序\",\n"
            + "      \"ka\": false,\n"
            + "      \"class\": \"com.fliggy.scm.product.client.model.productChannel.FscRouteChannelListDTO\",\n"
            + "      \"routeName\": \"杭州-考文垂 6天5夜超级豪华策士线路\"\n"
            + "    },\n"
            + "    {\n"
            + "      \"supplierName\": \"杭州阿信巴拉巴拉公司\",\n"
            + "      \"confirmTypeName\": \"即时确认\",\n"
            + "      \"routeCode\": \"FRC1016\",\n"
            + "      \"routeId\": \"2cecba02-11fd-42ab-b566-60a0b49cba8f\",\n"
            + "      \"bizChannelList\": [\n"
            + "        {\n"
            + "          \"channelType\": \"PLATFORM\",\n"
            + "          \"channelStatus\": \"ON_SALE\",\n"
            + "          \"class\": \"com.fliggy.scm.product.client.model.productChannel.FscBizChannelDTO\"\n"
            + "        },\n"
            + "        {\n"
            + "          \"channelType\": \"WECHAT_MINI_PROGRAM\",\n"
            + "          \"channelStatus\": \"OFF_SALE\",\n"
            + "          \"class\": \"com.fliggy.scm.product.client.model.productChannel.FscBizChannelDTO\"\n"
            + "        },\n"
            + "        {\n"
            + "          \"channelType\": \"FLIGGY\",\n"
            + "          \"channelStatus\": \"OFF_SALE\",\n"
            + "          \"class\": \"com.fliggy.scm.product.client.model.productChannel.FscBizChannelDTO\"\n"
            + "        }\n"
            + "      ],\n"
            + "      \"suggestChannelName\": \"阿信分销平台\",\n"
            + "      \"ka\": false,\n"
            + "      \"class\": \"com.fliggy.scm.product.client.model.productChannel.FscRouteChannelListDTO\",\n"
            + "      \"routeName\": \"杭州-考文垂 6天5夜超级豪华策士线路\"\n"
            + "    },\n"
            + "    {\n"
            + "      \"supplierName\": \"杭州阿信巴拉巴拉公司\",\n"
            + "      \"confirmTypeName\": \"即时确认\",\n"
            + "      \"routeCode\": \"FRC1015\",\n"
            + "      \"routeId\": \"51cf99e1-fbac-4d9e-a3fe-62cada198a4f\",\n"
            + "      \"bizChannelList\": [\n"
            + "        {\n"
            + "          \"channelType\": \"PLATFORM\",\n"
            + "          \"channelStatus\": \"ON_SALE\",\n"
            + "          \"class\": \"com.fliggy.scm.product.client.model.productChannel.FscBizChannelDTO\"\n"
            + "        },\n"
            + "        {\n"
            + "          \"channelType\": \"WECHAT_MINI_PROGRAM\",\n"
            + "          \"channelStatus\": \"OFF_SALE\",\n"
            + "          \"class\": \"com.fliggy.scm.product.client.model.productChannel.FscBizChannelDTO\"\n"
            + "        },\n"
            + "        {\n"
            + "          \"channelType\": \"FLIGGY\",\n"
            + "          \"channelStatus\": \"OFF_SALE\",\n"
            + "          \"class\": \"com.fliggy.scm.product.client.model.productChannel.FscBizChannelDTO\"\n"
            + "        }\n"
            + "      ],\n"
            + "      \"suggestChannelName\": \"阿信分销平台\",\n"
            + "      \"ka\": false,\n"
            + "      \"class\": \"com.fliggy.scm.product.client.model.productChannel.FscRouteChannelListDTO\",\n"
            + "      \"routeName\": \"杭州-考文垂 6天5夜超级豪华策士线路\"\n"
            + "    },\n"
            + "    {\n"
            + "      \"supplierName\": \"杭州阿信巴拉巴拉公司\",\n"
            + "      \"confirmTypeName\": \"即时确认\",\n"
            + "      \"routeCode\": \"FRC1014\",\n"
            + "      \"routeId\": \"0058c481-79d3-4397-970f-f770e5df761d\",\n"
            + "      \"bizChannelList\": [\n"
            + "        {\n"
            + "          \"channelType\": \"PLATFORM\",\n"
            + "          \"channelStatus\": \"ON_SALE\",\n"
            + "          \"class\": \"com.fliggy.scm.product.client.model.productChannel.FscBizChannelDTO\"\n"
            + "        },\n"
            + "        {\n"
            + "          \"channelType\": \"WECHAT_MINI_PROGRAM\",\n"
            + "          \"channelStatus\": \"OFF_SALE\",\n"
            + "          \"class\": \"com.fliggy.scm.product.client.model.productChannel.FscBizChannelDTO\"\n"
            + "        },\n"
            + "        {\n"
            + "          \"channelType\": \"FLIGGY\",\n"
            + "          \"channelStatus\": \"OFF_SALE\",\n"
            + "          \"class\": \"com.fliggy.scm.product.client.model.productChannel.FscBizChannelDTO\"\n"
            + "        }\n"
            + "      ],\n"
            + "      \"suggestChannelName\": \"阿信分销平台\",\n"
            + "      \"ka\": false,\n"
            + "      \"class\": \"com.fliggy.scm.product.client.model.productChannel.FscRouteChannelListDTO\",\n"
            + "      \"routeName\": \"杭州-考文垂 6天5夜超级豪华策士线路\"\n"
            + "    },\n"
            + "    {\n"
            + "      \"supplierName\": \"杭州阿信巴拉巴拉公司\",\n"
            + "      \"confirmTypeName\": \"即时确认\",\n"
            + "      \"routeCode\": \"FRC1013\",\n"
            + "      \"routeId\": \"93ae1221-b80e-4c96-986b-17af29857041\",\n"
            + "      \"bizChannelList\": [\n"
            + "        {\n"
            + "          \"channelType\": \"PLATFORM\",\n"
            + "          \"channelStatus\": \"ON_SALE\",\n"
            + "          \"class\": \"com.fliggy.scm.product.client.model.productChannel.FscBizChannelDTO\"\n"
            + "        },\n"
            + "        {\n"
            + "          \"channelType\": \"WECHAT_MINI_PROGRAM\",\n"
            + "          \"channelStatus\": \"OFF_SALE\",\n"
            + "          \"class\": \"com.fliggy.scm.product.client.model.productChannel.FscBizChannelDTO\"\n"
            + "        },\n"
            + "        {\n"
            + "          \"channelType\": \"FLIGGY\",\n"
            + "          \"channelStatus\": \"OFF_SALE\",\n"
            + "          \"class\": \"com.fliggy.scm.product.client.model.productChannel.FscBizChannelDTO\"\n"
            + "        }\n"
            + "      ],\n"
            + "      \"suggestChannelName\": \"阿信分销平台\",\n"
            + "      \"ka\": false,\n"
            + "      \"class\": \"com.fliggy.scm.product.client.model.productChannel.FscRouteChannelListDTO\",\n"
            + "      \"routeName\": \"杭州-考文垂 6天5夜超级豪华策士线路\"\n"
            + "    },\n"
            + "    {\n"
            + "      \"supplierName\": \"杭州阿信巴拉巴拉公司\",\n"
            + "      \"confirmTypeName\": \"即时确认\",\n"
            + "      \"routeCode\": \"FRC1012\",\n"
            + "      \"routeId\": \"23c12be1-dedf-4bd8-acb5-68b455355ce6\",\n"
            + "      \"bizChannelList\": [\n"
            + "        {\n"
            + "          \"channelType\": \"PLATFORM\",\n"
            + "          \"channelStatus\": \"ON_SALE\",\n"
            + "          \"class\": \"com.fliggy.scm.product.client.model.productChannel.FscBizChannelDTO\"\n"
            + "        },\n"
            + "        {\n"
            + "          \"channelType\": \"WECHAT_MINI_PROGRAM\",\n"
            + "          \"channelStatus\": \"OFF_SALE\",\n"
            + "          \"class\": \"com.fliggy.scm.product.client.model.productChannel.FscBizChannelDTO\"\n"
            + "        },\n"
            + "        {\n"
            + "          \"channelType\": \"FLIGGY\",\n"
            + "          \"channelStatus\": \"OFF_SALE\",\n"
            + "          \"class\": \"com.fliggy.scm.product.client.model.productChannel.FscBizChannelDTO\"\n"
            + "        }\n"
            + "      ],\n"
            + "      \"suggestChannelName\": \"阿信分销平台\",\n"
            + "      \"ka\": false,\n"
            + "      \"class\": \"com.fliggy.scm.product.client.model.productChannel.FscRouteChannelListDTO\",\n"
            + "      \"routeName\": \"杭州-考文垂 6天5夜超级豪华策士线路\"\n"
            + "    },\n"
            + "    {\n"
            + "      \"supplierName\": \"杭州阿信巴拉巴拉公司\",\n"
            + "      \"confirmTypeName\": \"即时确认\",\n"
            + "      \"routeCode\": \"FRC1011\",\n"
            + "      \"routeId\": \"d5ffc826-a40c-468b-94cc-493e7b354b11\",\n"
            + "      \"bizChannelList\": [\n"
            + "        {\n"
            + "          \"channelType\": \"PLATFORM\",\n"
            + "          \"channelStatus\": \"ON_SALE\",\n"
            + "          \"class\": \"com.fliggy.scm.product.client.model.productChannel.FscBizChannelDTO\"\n"
            + "        },\n"
            + "        {\n"
            + "          \"channelType\": \"WECHAT_MINI_PROGRAM\",\n"
            + "          \"channelStatus\": \"OFF_SALE\",\n"
            + "          \"class\": \"com.fliggy.scm.product.client.model.productChannel.FscBizChannelDTO\"\n"
            + "        },\n"
            + "        {\n"
            + "          \"channelType\": \"FLIGGY\",\n"
            + "          \"channelStatus\": \"OFF_SALE\",\n"
            + "          \"class\": \"com.fliggy.scm.product.client.model.productChannel.FscBizChannelDTO\"\n"
            + "        }\n"
            + "      ],\n"
            + "      \"suggestChannelName\": \"阿信分销平台\",\n"
            + "      \"ka\": false,\n"
            + "      \"class\": \"com.fliggy.scm.product.client.model.productChannel.FscRouteChannelListDTO\",\n"
            + "      \"routeName\": \"杭州-考文垂 6天5夜超级豪华策士线路\"\n"
            + "    }\n"
            + "  ]";
        JSONArray jsonArray = JSON.parseArray(dataArr);
        StringBuilder sb = new StringBuilder();
        for (Object o : jsonArray) {
            JSONObject obj = JSON.parseObject(JSON.toJSONString(o));
            sb.append(obj.get("routeId")).append(",");
        }
        System.out.println(sb);
    }

    @Test
    public void testJsonPathEval() {
        String jsonDemo = "{\n"
            + "    \"status\": 200,\n"
            + "    \"msg\": \"成功\",\n"
            + "    \"data\":\n"
            + "    {\n"
            + "        \"name\": \"Smith\",\n"
            + "        \"age\": 15,\n"
            + "        \"address\": \"青岛\"\n"
            + "    }\n"
            + "}";

        String jsonArrayDemo = "[\n"
            + "        {\n"
            + "            \"name\": \"Lucy\",\n"
            + "            \"age\": 10,\n"
            + "            \"address\": \"上海\"\n"
            + "        },\n"
            + "        {\n"
            + "            \"name\": \"Tom\",\n"
            + "            \"age\": 12,\n"
            + "            \"address\": \"北京\"\n"
            + "        },\n"
            + "        {\n"
            + "            \"name\": \"Smith\",\n"
            + "            \"age\": 15,\n"
            + "            \"address\": \"青岛\"\n"
            + "        },\n"
            + "        {\n"
            + "            \"name\": \"Jerry\",\n"
            + "            \"age\": 21,\n"
            + "            \"address\": \"秦皇岛\"\n"
            + "        }\n"
            + "    ]\n";
        JSONObject jsonObject = JSONObject.parseObject(jsonDemo);
        String path = "$.data.name";
        String response = (String) JSONPath.eval(jsonObject, path);
        System.out.printf("路径：%s，单个提取：%s\n", path, response);

        JSONArray jsonArray = JSON.parseArray(jsonArrayDemo);
        String arrayPath = "[1].name";
        String responseArray = (String)JSONPath.eval(jsonArray, arrayPath);
        System.out.printf("路径：%s，单个提取：%s\n", arrayPath, responseArray);
    }

    @Test
    public void testJSONClassParse() {
        // @type为JSONObject，反序列化为Map<String,Object>成功
        String jsonStr1 = "{\"@type\":\"com.alibaba.fastjson.JSONObject\",\"signAlipayAgent\":false}";
        Map<String, Object> map = JSON.parseObject(jsonStr1, new TypeReference<Map<String, Object>>() {
        });
        System.out.println(map);

        // @type为HashMap，反序列化为JSONObject成功
        String jsonStr2 = "{\"@type\":\"java.util.HashMap\",\"signAlipayAgent\":true}";
        JSONObject jsonObject = JSON.parseObject(jsonStr2, JSONObject.class);
        System.out.println(jsonObject);

        // @type为JSONObject，反序列化为Map<String,String>成功
        String jsonStr3 = "{\"@type\":\"com.alibaba.fastjson.JSONObject\",\"signAlipayAgent\":false}";
        Map<String, String> map3 = JSON.parseObject(jsonStr3, new TypeReference<Map<String, String>>() {
        });
        System.out.println(map3);
    }

    @Test
    public void testJSONObjectParse() {
        // @type是JSONObject，能正常反序列化为JSONObject
        String jsonStr1 = "{\"@type\":\"com.alibaba.fastjson.JSONObject\",\"signAlipayAgent\":false}";
        JSONObject extendInfo1 = JSON.parseObject(jsonStr1);
        System.out.println(extendInfo1.toJSONString());
        // @type不是JSONObject，不会影响反序列化为JSONObject
        String jsonStr2 = "{\"@type\":\"java.util.HashMap\",\"signAlipayAgent\":true}";
        JSONObject extendInfo2 = JSON.parseObject(jsonStr2);
        System.out.println(extendInfo2.toJSONString());
        // @type为空，也能正常反序列化为JSONObject
        String jsonStr3 = "{\"signAlipayAgent\":true}";
        JSONObject extendInfo3 = JSON.parseObject(jsonStr3);
        System.out.println(extendInfo3.toJSONString());
        // @type为不存在的类，会报错
        String jsonStr4 = "{\"@type\":\"com.trevzhang.Bean\",\"signAlipayAgent\":true}";
        JSONObject extendInfo4 = JSON.parseObject(jsonStr4);
        System.out.println(extendInfo4.toJSONString());
    }

    @Test
    public void testJsonObject() {
        JSONObject jsonObject = new JSONObject();
        jsonObject.put("agreementNo", "202204240627001");

        System.out.println((jsonObject.get("agreementNo")).getClass());

        String agreementNo = (String) jsonObject.get("agreementNo");
        System.out.println("agreementNo: " + agreementNo);
    }
}
